### ISSUE TITLE
AMPI with RealForward

### ISSUE THREAD

**Issue by benno90** [SciCompKL/MeDiPack#2]
I was using the AMPI library for reverse mode automatic differentiation
with the following includes and defines:

`include <codi.hpp>`
`#include <medi/medi.hpp>`
`#include <codi/externals/codiMediPackTypes.hpp>`
`using namespace medi;`
`using scalar = codi::RealReverse;`
`//using scalar = codi::RealForward;`
`#define TOOL CoDiPackTool<scalar>`
`#define MPI_SCALAR TOOL::MPI_TYPE`

Now I tried to compile the application with the RealForward type. Unfortunately, the compilation fails.
Should the Forward type also work with AMPI? If yes, do I need to make more adjustments than just changing the scalar type?

**Comment by MaxSagebaum** [comment]
Yes you need to include different files and classes:

```
#include <codi/externals/codiForwardMediPackTypes.hpp>
#define TOOL CoDiPackForwardTool<scalar>
```
The rest should stay the same.

**Comment by benno90** [comment]
Thanks, that worked. 
By the way, after testing different AD tools I can say that the CoDi and MeDiPack libraries are really easy to use and the performance is excellent!
